spring.datasource.url=jdbc:postgresql://localhost:5432/gen
spring.datasource.username=gen
spring.datasource.password=gen
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true